#!/usr/bin/env python3
"""Restore-fidelity determinism probe.

WHY: post-6a, a settle may reconstruct by restoring a captured snapshot rather
than rewinding. On ring-backed SWA layers (gpt-oss, gemma) that round trip has
NEVER been exercised — gpt-oss never published before Task 4's Harmony skip was
removed, kimi has no SWA rings, and qwen36's attention layers aren't ring-backed.
A capture that mishandled ring state would restore silently-wrong attention
windows: wrong context, no crash, no SHA failure (the store verifies storage
integrity, not capture completeness).

METHOD: same conversation, temperature 0, run twice — once with the prompt cache
OFF (cold prefill every turn, no capture/restore anywhere) and once with it ON
(settles, captures, restores). At temperature 0 the generated bytes must be
identical. Any divergence on a ring-backed model implicates ring capture before
anything in v6.

Determinism at temperature 0 on this stack is not assumed — it was observed:
the 2026-08-27 tool-loop probe produced a byte-identical turn 1 (114 completion
tokens, identical arguments_raw) across two different server binaries.

RUN AS: two passes against two server configurations, then --compare.
  pass 1:  server with the prompt cache OFF  -> restore_fidelity_off.json
  pass 2:  server with the prompt cache ON   -> restore_fidelity_on.json
  then:    restore_fidelity_probe.py --compare

v24 retired --prompt-cache-mode, so pass 1 is no longer reachable from argv. The
mode is a ModelSessionPlan parameter defaulted to multi-prefix, which is pass 2;
to run pass 1, build a server that constructs the plan with .off. The capability
is intact and only the argument is gone, but this probe is a two-pass A/B and one
of its passes now costs an edit rather than a flag.
"""
import json
import os
import sys
import time
import urllib.request

URL = "http://127.0.0.1:8081/v1/chat/completions"

# Long enough to force a settle and a subsequent restore, short enough to run twice.
TURNS = [
    "Name three rivers in Europe. One short sentence each.",
    "Which of those is longest? One sentence.",
    "Name a city on that river. One sentence.",
    "What country is that city in? One sentence.",
]


# Budget is per-model: qwen36 needs ~1500, gpt-oss reasons far longer and
# truncates there. A cut turn is not a fidelity test, so make it settable
# rather than hardcoding a second model-specific constant.
MAX_NEW = int(os.environ.get('PROBE_MAX_NEW', '1500'))


def post(model, messages, max_tokens=None):
    max_tokens = max_tokens or MAX_NEW
    body = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0,
    }
    req = urllib.request.Request(
        URL, data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=3600) as r:
        return json.load(r)


def run(model, out_path):
    msgs, record = [], []
    for i, t in enumerate(TURNS):
        msgs.append({"role": "user", "content": t})
        t0 = time.time()
        resp = post(model, msgs)
        wall = time.time() - t0
        ch = resp["choices"][0]
        m = ch["message"]
        u = resp.get("usage", {})
        content = m.get("content") or ""
        reasoning = m.get("reasoning_content") or ""
        record.append({
            "turn": i + 1,
            "content": content,
            "reasoning": reasoning,
            "prompt_tokens": u.get("prompt_tokens"),
            "completion_tokens": u.get("completion_tokens"),
            "wall": round(wall, 2),
            "finish": ch.get("finish_reason"),
        })
        print(f"turn{i+1}: wall={wall:.1f}s prompt={u.get('prompt_tokens')} "
              f"completion={u.get('completion_tokens')} "
              f"content_len={len(content)} reasoning_len={len(reasoning)} "
              f"finish={ch.get('finish_reason')}",
              flush=True)
        a = {"role": "assistant", "content": content}
        if reasoning:
            a["reasoning_content"] = reasoning
        msgs.append(a)
    with open(out_path, "w") as f:
        json.dump(record, f, indent=2)
    print(f"wrote {out_path}", flush=True)


def compare(a_path, b_path):
    a = json.load(open(a_path))
    b = json.load(open(b_path))
    ok = True
    for x, y in zip(a, b):
        same_c = x["content"] == y["content"]
        same_r = x["reasoning"] == y["reasoning"]
        # A divergence only means anything if both passes saw the SAME input.
        # Unequal prompt_tokens means the two conversations drifted apart, and
        # comparing their outputs says nothing about restore fidelity.
        comparable = x["prompt_tokens"] == y["prompt_tokens"]
        # A turn cut at the SAME cap from the SAME prompt is still a valid
        # comparison OF THAT TURN - both sides generated the same budget from
        # the same input. Truncation only invalidates turns AFTER it, because a
        # cut turn diverges the conversation downstream.
        both_cut = x.get("finish") == "length" == y.get("finish")
        same_budget = x["completion_tokens"] == y["completion_tokens"]
        one_cut = ("length" in (x.get("finish"), y.get("finish"))) and not both_cut
        if not comparable:
            flag = "INCOMPARABLE (inputs differ - probe defect, not a finding)"
        elif one_cut:
            flag = "INCOMPARABLE (one side cut, the other ran on)"
        elif both_cut and not same_budget:
            flag = "INCOMPARABLE (both cut, different budgets)"
        else:
            flag = "MATCH" if (same_c and same_r) else "DIVERGED"
            if both_cut:
                flag += " [both cut at the same cap: valid for THIS turn, "
                flag += "downstream turns contaminated]"
        if not comparable or one_cut or (both_cut and not same_budget) \
                or not (same_c and same_r):
            ok = False
        print(f"turn{x['turn']}: {flag} "
              f"content={'=' if same_c else 'X'} reasoning={'=' if same_r else 'X'} "
              f"(cold prompt={x['prompt_tokens']} vs cached prompt={y['prompt_tokens']})",
              flush=True)
        if not same_c:
            print(f"    cold  : {x['content'][:160]!r}", flush=True)
            print(f"    cached: {y['content'][:160]!r}", flush=True)
    print("\nVERDICT: " + ("IDENTICAL — restore fidelity holds"
                           if ok else "NOT CLEAN — read the per-turn flags above; "
                                     "only a comparable, untruncated DIVERGED "
                                     "implicates capture/restore"),
          flush=True)
    return 0 if ok else 1


if __name__ == "__main__":
    if sys.argv[1] == "--compare":
        sys.exit(compare(sys.argv[2], sys.argv[3]))
    run(sys.argv[1], sys.argv[2])
